name: SimpleVQA
num_epochs: 5
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 4
num_workers: 6

data:  
   
    train:
        type: ViewDecompositionDataset_add_forSimpleVQA
        args:
            weight: 0.540
            phase: train
            anno_file: D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\train\train_data.csv
            data_prefix: D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\train\video
            data_prefix_3D:  D:\code\KVQ-Challenge-CVPR-NTIRE2024\feature\simpleVQA\kvq
            feature_type: SlowFast
            sample_types:
                simpleVQA:
                    resize: 520
                    crop: 448
                    clip_len: 8
                    frame_interval: 10
                    t_frag: 8
                    num_clips: 1
            
    
    val:
        type: ViewDecompositionDataset_add_forSimpleVQA
        args:
            phase: test
            anno_file:  D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\val\val_data.csv
            data_prefix: D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\train\video
            data_prefix_3D: D:\code\KVQ-Challenge-CVPR-NTIRE2024\feature\simpleVQA\kvq
            feature_type: SlowFast
            sample_types: 
                simpleVQA:
                    resize: 520
                    crop: 448
                    clip_len: 8
                    frame_interval: 10
                    t_frag: 8
                    num_clips: 1
            

model:
    type: simpleVQA
    args:
        simpleVQA:
            backbone:
            head:
                in_channels: 9472
                hidden_channels: 128
        
optimizer:
    lr: !!float 3e-5
    backbone_lr_mult: !!float 1
    wd: 0.05
        
load_path: checkpoint\SimpleVQA_epoch_6_head_val-ltest_s_finetuned.pth
test_load_path: checkpoint\SimpleVQA_epoch_6_head_val-ltest_s_finetuned.pth

    
        
