name: simpleVQA
num_epochs: 20
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 8
num_workers: 12


data:  
    
    
    val:
        type: ViewDecompositionDataset_add_forSimpleVQA
        args:
            phase: test
            anno_file:  D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\test_final\test_data.csv
            data_prefix: D:\code\KVQ-Challenge-CVPR-NTIRE2024\KVQ\test_final
            data_prefix_3D: D:\code\KVQ-Challenge-CVPR-NTIRE2024\feature\simpleVQA\kvq
            feature_type: SlowFast
            sample_types: 
                simpleVQA:
                    resize: 520
                    crop: 448
                    clip_len: 8
                    frame_interval: 10
                    t_frag: 8
                    num_clips: 1
            

model:
    type: simpleVQA
    args:
        simpleVQA:
            backbone:
            head:
                in_channels: 9472
                hidden_channels: 128
            
optimizer:
    lr: !!float 3e-5
    backbone_lr_mult: !!float 1
    wd: 0.05

load_path: checkpoint\SimpleVQA_epoch_6_head_val-ltest_s_finetuned.pth
test_load_path: checkpoint\SimpleVQA_epoch_6_head_val-ltest_s_finetuned.pth

load_path2: checkpoint\SimpleVQA_epoch_0_head_val-ltest_s_finetuned.pth
test_load_path2: checkpoint\SimpleVQA_epoch_0_head_val-ltest_s_finetuned.pth

    
        
